### ISSUE TITLE
Null audio characteristics

### ISSUE THREAD

**Issue by vanboom** [fabnicol/dvda-author#1]
I recently upgraded my pc to AMD on Ubuntu 16.04 and am no longer able to use a pre-built deb package of dvda-author-09.03. 

I was able to build dvda-author from source, but am getting a `Null audio characteristics` error when using some .flac music files.  This error does not occur with the old version. 

```
./mysong.flac  Null audio characteristics
[INF]  Fixwav repair was unsuccessful; file will be skipped.

```
Thanks for dvda-author.  It is amazing.

**Comment by fabnicol** [comment]
Hi
Which version of the source code are you using?

**Comment by vanboom** [comment]
I am using the master branch from this repository.  I was not able to build some of the dependent libraries also, like mjpegtools-2.1.0, the configurator was complaining about GCC not supporting i386.  I would be happy to contribute any fixes as a PR.  Appreciate your help.

**Comment by fabnicol** [comment]
OkCould you possibly try the latest linux dev builds on sourceforge https://sourceforge.net/projects/dvd-audio/files/dvda-author/dvda-author-dev/Either the ubuntu or gentoo build

-------- Message d'origine --------
De : Don <notifications@github.com> 
Date : 22/04/2018  17:55  (GMT+01:00) 
À : fabnicol/dvda-author <dvda-author@noreply.github.com> 
Cc : fabnicol <fabrnicol@gmail.com>, Comment <comment@noreply.github.com> 
Objet : Re: [fabnicol/dvda-author] Null audio characteristics (#1) 

I am using the master branch from this repository.  I was not able to build some of the dependent libraries also, like mjpegtools-2.1.0, the configurator was complaining about GCC not supporting i386.  I would be happy to contribute any fixes as a PR.  Appreciate your help.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fabnicol/dvda-author","title":"fabnicol/dvda-author","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fabnicol/dvda-author"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vanboom in #1: I am using the master branch from this repository.  I was not able to build some of the dependent libraries also, like mjpegtools-2.1.0, the configurator was complaining about GCC not supporting i386.  I would be happy to contribute any fixes as a PR.  Appreciate your help."}],"action":{"name":"View Issue","url":"https://github.com/fabnicol/dvda-author/issues/1#issuecomment-383391455"}}}

**Comment by vanboom** [comment]
Yes - following the instructions in TEST, some shared libraries are missing: libssp.so.0.  I set the LD_LIBRARY_PATH as instructed.  libpng was also missing, but I was able to install that using apt.

**Comment by fabnicol** [comment]
OK,
libssp is a by-product of building gcc from source code.
Either you build gcc (7.3) from source code (say from:

http://mirrors-usa.go-parts.com/gcc/releases/gcc-7.3.0/gcc-7.3.0.tar.gz

using:

  ./configure --enable-languages=c,c++)

or you use the attached libssp compressed folder and unpack the libs to
/usr/local/lib64
Then please report.
I have no issue using flac audio on my side.
Thanks.

2018-04-22 20:41 GMT+02:00 Don <notifications@github.com>:

**Comment by vanboom** [comment]
I installed gcc-7 and that has satisfied the libssp dependency.  Running the build version of dvda-audio-dev results in the same error.  I am specifying the -F option, but get the same error even if I remove the -F. 

I also have a dvda-author.conf in the same directory, but everything is commented except `debug`, `pause` and `rights 0777`. 

This publicly available .flac file gives the same error: http://www.eclassical.com/custom/eclassical/files/BIS1536-001-flac_16.flac

I am going to try to work through the build issues to see if I can get a binary that I can debug with.

**Comment by fabnicol** [comment]
Hi Don,
Nice report, thanks.
I'll try to replicate (so far my flacs have worked).
I've been lately working quite a bit on lplex (which I've forked, the
author being out of reach or perhaps deceased, I don't know.)
Lplex will be integrated in the dvda-author tree, which will allow
straightforward creation of so-called "hybrid" DVD-Audio/Video discs.
Best,
Fabrice

2018-04-27 0:30 GMT+02:00 Don <notifications@github.com>:

**Comment by fabnicol** [comment]
What about the new build on sourceforge
https://sourceforge.net/projects/dvd-audio/files/dvda-author/dvda-author-dev/linux%20%2B%20source%20%28Gentoo%20amd64%20build%29/dvda-author-dev-20180427.tar.xz/download
(Follow instructions given in enclosed file TEST)

2018-04-27 0:30 GMT+02:00 Don <notifications@github.com>:

**Comment by vanboom** [comment]
Another data point, it works perfectly for .wav files that were converted from the .flac

**Comment by vanboom** [comment]
The new build worked perfectly.

**Comment by vanboom** [comment]
I was able to get my build to work by simplifying the features: 

`./configure --enable-flac-build --enable-ogg-build --enable-sox-build`

I then followed the normal process `make` and `sudo make install`.  

Possibly my prior build did not have flac enabled, which was causing the "Null audio characteristics" error?

**Comment by vanboom** [comment]
Closing this issue, as I am now able to get a binary built in Ubuntu 16.04 that works.

**Comment by fabnicol** [comment]
That's it.

-------- Message d'origine --------
De : Don <notifications@github.com> 
Date : 28/04/2018  16:55  (GMT+01:00) 
À : fabnicol/dvda-author <dvda-author@noreply.github.com> 
Cc : fabnicol <fabrnicol@gmail.com>, Comment <comment@noreply.github.com> 
Objet : Re: [fabnicol/dvda-author] Null audio characteristics (#1) 

I was able to get my build to work by simplifying the features:
./configure --enable-flac-build --enable-ogg-build --enable-sox-build
I then followed the normal process make and sudo make install.
Possibly my prior build did not have flac enabled, which was causing the "Null audio characteristics" error?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fabnicol/dvda-author","title":"fabnicol/dvda-author","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fabnicol/dvda-author"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vanboom in #1: I was able to get my build to work by simplifying the features: \r\n\r\n`./configure --enable-flac-build --enable-ogg-build --enable-sox-build`\r\n\r\nI then followed the normal process `make` and `sudo make install`.  \r\n\r\nPossibly my prior build did not have flac enabled, which was causing the \"Null audio characteristics\" error?   "}],"action":{"name":"View Issue","url":"https://github.com/fabnicol/dvda-author/issues/1#issuecomment-385181839"}}}
